exclude: 'docs/build/'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=4000']
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        exclude: 'docs/make.bat'
        args: ['--fix=lf']
      - id: name-tests-test
        args: ['--pytest-test-first']
      - id: pretty-format-json
        exclude_types: [jupyter]
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
     - id: pyupgrade

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-pyproject]

  - repo: https://github.com/pycqa/isort
    rev: 9.0.0b2
    hooks:
      - id: isort
