[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "BioSonic"
version = "0.0"
dependencies = [
  exceptiongroup>=1.2.2,
  iniconfig>=2.1.0,
  numpy>=2.2.4,
  packaging>=24.2,
  pluggy>=1.5.0,
  pytest>=8.3.5,
  scipy>=1.15.2,
  tomli>=2.2.1,
]

requires-python = ">=3.8"

authors = [
  {name = "Lena Gies", email = "a12113065@unet.univie.ac.at"},
  {name = "Tecumseh Fitch", email = ""},
]
maintainers = [
  {name = "Lena Gies", email = "a12113065@unet.univie.ac.at"}
]

description = "The BioSonic package contains tools for bioacoustic analysis."
readme = "README.md"
keywords = ["bioacoustics", "signal", "sound synthesis", "biology", "singal processing"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python",
  "License :: MIT"
]

[project.optional-dependencies]
praat = [
  "praat-parselmouth>=0.4.5",
]

[project.urls]
Homepage = "https://github.com/lenag23/biosonic.git"
Documentation = "https://readthedocs.org"
Repository = "https://github.com/lenag23/biosonic.git"
"Bug Tracker" = "https://github.com/lenag23/biosonic/issues"

[project.scripts]
biosonic-cli = "biosonic:main_cli"