[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
strict = true
show_error_codes = true
pretty = true
exclude = ["tests/", "build/", "dist/", "docs/", "normalized/"]

[project]
name = "biosonic_lenag23"
version = "0.0.1"
dependencies = [
  "matplotlib>=3.9.4",
  "numpy>=1.26.4",
  "pandas>=2.3.0",
  "scipy>=1.12"
]

requires-python = ">=3.9"

authors = [
  {name = "Lena Gies", email = "lena.gies@univie.ac.at"},
  {name = "Tecumseh Fitch", email = "tecumseh.fitch@unet.univie.ac.at"},
  {name = "Yannick Jadoul", email="yannick.jadoul@uniroma1.it"}
]
maintainers = [
  {name = "Lena Gies", email = "lena.gies@univie.ac.at"}
]

description = "The BioSonic package contains tools for bioacoustic analysis."
readme = {file = "README.md", content-type = "text/markdown"}
keywords = ["bioacoustics", "signal", "sound synthesis", "biology", "singal processing"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python",
  "License :: BSD-3-Clause"
]
license = "BSD-3-Clause"
license-files = ["LICENSE*"]

[project.optional-dependencies]
praat = ["praat-textgrids>=1.4.0"]

[project.urls]
Homepage = "https://github.com/lenag23/biosonic.git"
Documentation = "https://readthedocs.org" # update after registering
Repository = "https://github.com/lenag23/biosonic.git"
"Bug Tracker" = "https://github.com/lenag23/biosonic/issues"

[tool.flake8]
max-line-length = 160
max-doc-length = 100
extend-ignore = [
  "E125",  # reenable later?
  "E741",
  "W505",  # for now, ignore too long docstrings
]
per-file-ignores = [
  "__init__.py:F401",
  "tests/*:E402,F811",  # Remove after splitting up tests?
]

[tool.isort]
skip = ["docs/source/conf.py"]
line_length = 100
multi_line_output = 3
